Importing numpy

In [96]:
import numpy as np # type: ignore

Import a module from numpy

In [97]:
from numpy import array # type: ignore

importing everything from numpy

In [98]:
from numpy import * # type: ignore

array creation

     using np.array function


    using lists 

In [99]:
list1=[1,2,3,4,5,6,7,8,9,]
list_array=np.array(list1)
list_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

        by providing data type while creating a array(dtype function)

In [100]:
a = np.array([1,2,3,4,5,6,7,8,9,10],dtype="float")
a

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

       creating array with 2 or more lists(2 or more dimensional array)

In [101]:
array_2d = np.array(([1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]))
array_2d

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [1, 2, 3, 4, 5, 6, 7, 8, 9]])

      creating array using np.zeros("no of elements are written here)

In [102]:
zero_array= np.zeros(10)
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

        creating array with np.ones("no elements are witten here")
        array filled with ones

In [103]:
one_array= np.ones(10)
one_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

        creating array with np.empty(no. of elements)

In [104]:
slip_array=np.empty(10)
slip_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

    in the above code we tried to make a empty array but the array was not empty because the array takes place in memory and the other random values fill the empty space.In my case the ones from np.ones took place in the empty array

        creating array with arange function : np.arange(start value,stop value,step value)

In [105]:
arange_array= np.arange(1,11,1) # stop value is not included
arange_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

there are more ways we will talk about them later.

NOW WE WILL SEE SOME FUNCTIONS AND OPERATION ON ARRAYS

Ndarray.ndim

         Shows number of axes(Dimensions) a array has.

In [106]:
var1 = np.array([1,2,3,3,4,5,67,7,8,9])
var2 = np.array(([1,2,3,4,5,6,7,8,9,10],[11,22,33,44,55,66,77,88,99,100]),dtype="int64")
var2.ndim    ,    var1.ndim

(2, 1)

ndaray.shape

         ndarray.shape shows the dimensions of the array

In [107]:
print(var1.shape)
print(var2.shape)

(10,)
(2, 10)


ndarray.size

            ndarray.size shows the total number of elements of the array

In [108]:
print(var1.size)
print(var2.size)

10
20


ndarray.dtype

        ndarray.dtype is an object describing the type of the elements in the array

In [124]:
print(var1.dtype)
print(var2.dtype)

int32
int64


ndarray.itemsize

        ndarray.itemsize shows the size in bytes of each element of the array

In [110]:
print(var1.itemsize)
print(var2.itemsize)

4
8


ndarray.data

        ndarray.data the buffer containing the actual elements of the array

In [111]:
data1=var1.data
data2=var2.data
data1    ,    data2

(<memory at 0x000002A7EB0C0F40>, <memory at 0x000002A7EB0F60C0>)

ndarray.reshape (no. of lists [optional] , no. of rows , no. of coloumns)

        ndarray.reshape reshapes the array to dezired shape

In [112]:
reshape_intro = np.arange(1,101,1)
reshaped_intro = reshape_intro.reshape(5,5,4)
reshaped_intro

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12],
        [ 13,  14,  15,  16],
        [ 17,  18,  19,  20]],

       [[ 21,  22,  23,  24],
        [ 25,  26,  27,  28],
        [ 29,  30,  31,  32],
        [ 33,  34,  35,  36],
        [ 37,  38,  39,  40]],

       [[ 41,  42,  43,  44],
        [ 45,  46,  47,  48],
        [ 49,  50,  51,  52],
        [ 53,  54,  55,  56],
        [ 57,  58,  59,  60]],

       [[ 61,  62,  63,  64],
        [ 65,  66,  67,  68],
        [ 69,  70,  71,  72],
        [ 73,  74,  75,  76],
        [ 77,  78,  79,  80]],

       [[ 81,  82,  83,  84],
        [ 85,  86,  87,  88],
        [ 89,  90,  91,  92],
        [ 93,  94,  95,  96],
        [ 97,  98,  99, 100]]])

Ndarray.ravel()

        returns flattened array

In [113]:
print(var2,"(real array)")
print()#for space between
print(var2.ravel(),"(flattened array)")

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  22  33  44  55  66  77  88  99 100]] (real array)

[  1   2   3   4   5   6   7   8   9  10  11  22  33  44  55  66  77  88
  99 100] (flattened array)


Ndarray.T

        Return a transposed array
    

In [114]:
print(var2,"(real array)")
print()# for space between
print(var2.T,"(transposed array)")

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  22  33  44  55  66  77  88  99 100]] (real array)

[[  1  11]
 [  2  22]
 [  3  33]
 [  4  44]
 [  5  55]
 [  6  66]
 [  7  77]
 [  8  88]
 [  9  99]
 [ 10 100]] (transposed array)


np.hstack(parameters)

        it stacks two or more arrays horizontaly

In [115]:
print(np.hstack((var1,var2[0])))# we indexed var2 to make the bot array of the same size ,we will talk about indexing later.

[ 1  2  3  3  4  5 67  7  8  9  1  2  3  4  5  6  7  8  9 10]


np.vstack(parameters)

        it stacks two or more array verticaly.

In [116]:
print(var1,var2[0])

[ 1  2  3  3  4  5 67  7  8  9] [ 1  2  3  4  5  6  7  8  9 10]


np.colomn_stack

        The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D

In [121]:
A = np.column_stack((var1,var2[0]))
A

array([[ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [ 3,  4],
       [ 4,  5],
       [ 5,  6],
       [67,  7],
       [ 7,  8],
       [ 8,  9],
       [ 9, 10]], dtype=int64)

np.concatenate

        it concatenates two array to form one single array

In [126]:
concatenate_array = np.concatenate((var1,var2[0]))
print(concatenate_array)

[ 1  2  3  3  4  5 67  7  8  9  1  2  3  4  5  6  7  8  9 10]


np.hslipt()

        you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur

In [130]:
C=np.hsplit(var1,5)
C

[array([1, 2]), array([3, 3]), array([4, 5]), array([67,  7]), array([8, 9])]

np.vsplit

        you can split an array along its horizontal axis, either by specifying the number of equally shaped arrays to return, or by specifying the columns after which the division should occur

In [133]:
d=np.hsplit(var2,5)
d

[array([[ 1,  2],
        [11, 22]], dtype=int64),
 array([[ 3,  4],
        [33, 44]], dtype=int64),
 array([[ 5,  6],
        [55, 66]], dtype=int64),
 array([[ 7,  8],
        [77, 88]], dtype=int64),
 array([[  9,  10],
        [ 99, 100]], dtype=int64)]